export const defaultCVData = {
  title: 'Yeni CV',
  theme: 'modern',
  customize: {
    accentColor: '#6c63ff',
    fontPair: 'syne-dm',
    layout: 'two-column',
  },
  personalInfo: {
    fullName: '',
    jobTitle: '',
    email: '',
    phone: '',
    location: '',
    linkedin: '',
    github: '',
    website: '',
    photoURL: '',
    birthDate: '',
    nationality: '',
    drivingLicense: '',
    militaryStatus: '',
  },
  summary: '',
  experiences: [],
  education: [],
  skills: [],
  projects: [],
  languages: [],
  certifications: [],
};
